spring:
  application:
    name: AddressService
  datasource:
    # Use the Internal Database URL from Render for better performance
    url: jdbc:postgresql://dpg-d1gifiili9vc73ampq0g-a.oregon-postgres.render.com:5432/pp_8n61
    username: pp_8n61_user
    password: zAd8h00JbOYSthb9CpZ4SVGwyfPyEfjx
    driver-class-name: org.postgresql.Driver
    # Add connection pool settings for better reliability
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Add these properties for better connection handling
        connection.provider_disables_autocommit: true
        jdbc.time_zone: UTC

# Move server configuration to root level (not under spring)
server:
  port: ${PORT:8080}

# Add logging configuration for better debugging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
