spring:
  application:
    name: AddressService
  datasource:
    url: jdbc:mysql://localhost:3306/spb430
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082