spring:
  application:
    name: AddressService
  datasource:
    url: jdbc:postgresql://dpg-d1gifiil9vc73ampq0g-a:5432/pp_8n61
    username: pp_8n61_user
    password: zAd8h00JbOYSthb9CpZ4SVGwyfPyEfjx
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8082
